export default [
  {
    postId: 17,
    media: require("../FeedVideos/SnowBoard.mp4"),
    likes: 146,
    comments: 16,
    saves: 32,
    shares: 12,
    title: "Snowboarding – French Alps",
    subTitle: "Courchevel, France",
    description:
      "It’s not about the number of breaths you take, but the moments that take your breath away ",
    isVerified: true,
    isFollowing: true,
    userRating: 4.5,
    user: {
      userId: 17,
      username: "@Joe_Hannett",
      level: 11,
      phoneNumber: 2345678901,
      avatar: require("../FeedImages/Hiker.jpg"),
    },
    postVenue: {
      postVenueId: 18,
      venue: {
        venueId: 123456,
        isExternal: false,
        venuePrice: "63",
        type: "Experience",
      },
    },
  },
  {
    postId: 21,
    media: require("../FeedVideos/EDM1.mp4"),
    likes: 146,
    comments: 16,
    saves: 32,
    shares: 12,
    title: "Tomorrowland 2021 – Full Madness Pass",
    subTitle: "Boom, Belgium ",
    description:
      "First time going to Tomorrowland! Exhausted but what a day! #tired #letsdoitagain",
    isVerified: true,
    isFollowing: true,
    userRating: 3.5,
    user: {
      userId: 21,
      username: "@Devin_Brennan",
      level: 9,
      phoneNumber: 2345678901,
      avatar: require("../FeedImages/Hiker.jpg"),
    },
    postVenue: {
      postVenueId: 21,
      venue: {
        venueId: 123456,
        isExternal: false,
        venuePrice: "265",
        type: "Experience",
      },
    },
  },
  {
    postId: 18,
    media: require("../FeedVideos/JetskiUtah.mp4"),
    likes: 146,
    comments: 16,
    saves: 32,
    shares: 12,
    title: "Jet Ski in Lake Powell",
    subTitle: "St. George, Utah",
    description: "Day trip to Lake Powell! #funwithfriends #sundayfunday",
    isVerified: true,
    isFollowing: true,
    userRating: 3.5,
    user: {
      userId: 18,
      username: "@Mariah_Revis",
      level: 41,
      phoneNumber: 2345678901,
      avatar: require("../FeedImages/Hiker.jpg"),
    },
    postVenue: {
      postVenueId: 18,
      venue: {
        venueId: 123456,
        isExternal: false,
        venuePrice: "120",
        type: "Experience",
      },
    },
  },
  {
    postId: 19,
    media: require("../FeedVideos/AdrenalineRapids.mp4"),
    likes: 146,
    comments: 16,
    saves: 32,
    shares: 12,
    title: "Moose River Rafting Day Trip",
    subTitle: "Adirondacks, New York",
    description:
      "There’s nothing like whitewater rafting to make you feel alive! #yolo #travel #adirondacks",
    isVerified: false,
    userRating: 2.5,
    user: {
      userId: 19,
      username: "@Mike_DeLucca",
      level: 101,
      phoneNumber: 2345678901,
      avatar: require("../FeedImages/Hiker.jpg"),
    },
    postVenue: {
      postVenueId: 19,
      venue: {
        venueId: 123456,
        isExternal: false,
        venuePrice: "120",
        type: "Experience",
      },
    },
  },
  {
    postId: 20,
    media: require("../FeedVideos/ParisBalcony.mp4"),
    likes: 146,
    comments: 16,
    saves: 32,
    shares: 12,
    title: "Beautiful Restaurant with a View",
    subTitle: "Paris, France",
    description:
      "A local told us we just had to go to this restaurant. Amazing food and just look at that view! #wheninparis #afternooninparis #eiffeltower",
    isVerified: true,
    isFollowing: true,
    userRating: 1.5,
    user: {
      userId: 20,
      username: "@Veronica_Rivera",
      level: 31,
      phoneNumber: 2345678901,
      avatar: require("../FeedImages/Hiker.jpg"),
    },
    postVenue: {
      postVenueId: 20,
      venue: {
        venueId: 123456,
        isExternal: false,
        venuePrice: "85",
        type: "Experience",
      },
    },
  },
  {
    postId: 24,
    media: require("../FeedVideos/Alps.mp4"),
    likes: 546,
    comments: 56,
    saves: 32,
    shares: 12,
    title: "Alps Hiking",
    subTitle: "Bernese Oberland, Switzerland",
    description: "Vibes.",
    isVerified: true,
    isFollowing: true,
    userRating: 4,
    user: {
      userId: 24,
      username: "@Mariah_Revis",
      level: 41,
      phoneNumber: 2345678901,
      avatar: require("../FeedImages/Hiker.jpg"),
    },
    postVenue: {
      postVenueId: 24,
      venue: {
        venueId: 123456,
        isExternal: false,
        venuePrice: "199",
        type: "Experience",
      },
    },
  },
  {
    postId: 26,
    media: require("../FeedVideos/LookOut.mp4"),
    likes: 146,
    comments: 16,
    saves: 32,
    shares: 12,
    title: "Mount Marcey Lookout Sunset",
    subTitle: "Adirondacks, New York",
    description: "Amazing Views.",
    isVerified: false,
    userRating: 3,
    user: {
      userId: 26,
      username: "@Jessica_Tran",
      level: 111,
      phoneNumber: 2345678901,
      avatar: require("../FeedImages/Hiker.jpg"),
    },
    postVenue: {
      postVenueId: 26,
      venue: {
        venueId: 123456,
        isExternal: false,
        venuePrice: "245",
        type: "Experience",
      },
    },
  },
  {
    postId: 38,
    media: require("../FeedVideos/Dubai.mp4"),
    likes: 146,
    comments: 16,
    saves: 32,
    shares: 12,
    title: "Taj Dubai Pool View",
    subTitle: "Dubai, United Arab Emirates",
    description:
      "We were not expecting this view! It’s even more breathtaking in person! #relax #vacation #grateful",
    isVerified: false,
    userRating: 38,
    user: {
      userId: 12,
      username: "@Veronica_Rivera",
      level: 88,
      phoneNumber: 2345678901,
      avatar: require("../FeedImages/Hiker.jpg"),
    },
    postVenue: {
      postVenueId: 38,
      venue: {
        venueId: 123456,
        isExternal: false,
        venuePrice: "545",
        type: "Hotel",
      },
    },
  },
];
